# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InterfaceUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1031, 865)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(80, 60, 860, 760))
        self.frame.setMinimumSize(QtCore.QSize(860, 760))
        self.frame.setStyleSheet("#frame{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-bottom-left-radius:20px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:20px;\n"
"\n"
"border-top-right-radius:20px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setStyleSheet("border:None;\n"
"font: 18pt \"幼圆\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(35, 35))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout.addWidget(self.frame_4, 0, QtCore.Qt.AlignLeft)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_logout = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_logout.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_logout.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/退出.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_logout.setIcon(icon1)
        self.pushButton_logout.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_logout.setObjectName("pushButton_logout")
        self.horizontalLayout_2.addWidget(self.pushButton_logout)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/最小化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_4.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.horizontalLayout.addWidget(self.frame_5, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("#frame_6{\n"
"    background-color: rgb(85, 85, 127);\n"
"    border-bottom-left-radius:20px;\n"
"    border-top-right-radius:20px;\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font: 12pt \"幼圆\";\n"
"}\n"
"QPushButton:hover{\n"
"    color:rgb(168,168,168);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_3.addWidget(self.pushButton_7)
        self.pushButton_home = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_home.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_home.setObjectName("pushButton_home")
        self.verticalLayout_3.addWidget(self.pushButton_home)
        self.pushButton_web = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_web.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_web.setObjectName("pushButton_web")
        self.verticalLayout_3.addWidget(self.pushButton_web)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.pushButton_my = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_my.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_my.setObjectName("pushButton_my")
        self.verticalLayout_3.addWidget(self.pushButton_my)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("#frame_7{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-bottom-right-radius:20px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_7)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pagehome = QtWidgets.QWidget()
        self.pagehome.setObjectName("pagehome")
        self.label = QtWidgets.QLabel(self.pagehome)
        self.label.setGeometry(QtCore.QRect(180, 300, 281, 37))
        self.label.setMaximumSize(QtCore.QSize(620, 16777215))
        self.label.setStyleSheet("font: 20pt \"华文楷体\";\n"
"border:1px solid blue;\n"
"border-radius:5px;")
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.pagehome)
        self.page_web = QtWidgets.QWidget()
        self.page_web.setObjectName("page_web")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page_web)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_8 = QtWidgets.QFrame(self.page_web)
        self.frame_8.setMinimumSize(QtCore.QSize(400, 511))
        self.frame_8.setMaximumSize(QtCore.QSize(400, 511))
        self.frame_8.setStyleSheet("QPushButton{\n"
"    border:2px solid black;\n"
"    border-radius:7px;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(203, 203, 203);\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_BIBI = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_BIBI.setMinimumSize(QtCore.QSize(0, 30))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/bilibili.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_BIBI.setIcon(icon4)
        self.pushButton_BIBI.setObjectName("pushButton_BIBI")
        self.verticalLayout_4.addWidget(self.pushButton_BIBI)
        self.pushButton_CSDN = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_CSDN.setMinimumSize(QtCore.QSize(0, 30))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/csdn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_CSDN.setIcon(icon5)
        self.pushButton_CSDN.setObjectName("pushButton_CSDN")
        self.verticalLayout_4.addWidget(self.pushButton_CSDN)
        self.pushButton_APPLE = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_APPLE.setMinimumSize(QtCore.QSize(0, 30))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/icon-apple.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_APPLE.setIcon(icon6)
        self.pushButton_APPLE.setObjectName("pushButton_APPLE")
        self.verticalLayout_4.addWidget(self.pushButton_APPLE)
        self.pushButton_TV = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_TV.setMinimumSize(QtCore.QSize(0, 30))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/腾讯视频.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_TV.setIcon(icon7)
        self.pushButton_TV.setObjectName("pushButton_TV")
        self.verticalLayout_4.addWidget(self.pushButton_TV)
        self.horizontalLayout_5.addWidget(self.frame_8)
        self.stackedWidget.addWidget(self.page_web)
        self.page_my = QtWidgets.QWidget()
        self.page_my.setObjectName("page_my")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.page_my)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_9 = QtWidgets.QFrame(self.page_my)
        self.frame_9.setMinimumSize(QtCore.QSize(400, 511))
        self.frame_9.setMaximumSize(QtCore.QSize(400, 511))
        self.frame_9.setStyleSheet("QPushButton{\n"
"    border:2px solid black;\n"
"    border-radius:7px;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(203, 203, 203);\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit_L_M_pass1 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_L_M_pass1.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_L_M_pass1.setObjectName("lineEdit_L_M_pass1")
        self.verticalLayout_5.addWidget(self.lineEdit_L_M_pass1)
        self.lineEdit_L_M_pass2 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_L_M_pass2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_L_M_pass2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_L_M_pass2.setObjectName("lineEdit_L_M_pass2")
        self.verticalLayout_5.addWidget(self.lineEdit_L_M_pass2)
        self.pushButton_L_sure = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_L_sure.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_L_sure.setObjectName("pushButton_L_sure")
        self.verticalLayout_5.addWidget(self.pushButton_L_sure)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_9)
        self.stackedWidget_2.setMinimumSize(QtCore.QSize(0, 30))
        self.stackedWidget_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget_2.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget_2.addWidget(self.page_2)
        self.verticalLayout_5.addWidget(self.stackedWidget_2)
        self.horizontalLayout_6.addWidget(self.frame_9)
        self.stackedWidget.addWidget(self.page_my)
        self.horizontalLayout_4.addWidget(self.stackedWidget)
        self.horizontalLayout_3.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton_4.clicked.connect(MainWindow.close) # type: ignore
        self.pushButton_3.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "屏幕识别系统"))
        self.pushButton_home.setText(_translate("MainWindow", "首页"))
        self.pushButton_web.setText(_translate("MainWindow", "网址推荐"))
        self.pushButton_my.setText(_translate("MainWindow", "我的"))
        self.label.setText(_translate("MainWindow", "欢迎登录我的界面"))
        self.pushButton_BIBI.setText(_translate("MainWindow", "BiliBili"))
        self.pushButton_CSDN.setText(_translate("MainWindow", "CSDN"))
        self.pushButton_APPLE.setText(_translate("MainWindow", "APPLE"))
        self.pushButton_TV.setText(_translate("MainWindow", "TENCENT VIDEO"))
        self.lineEdit_L_M_pass1.setPlaceholderText(_translate("MainWindow", "密码："))
        self.lineEdit_L_M_pass2.setPlaceholderText(_translate("MainWindow", "确认密码："))
        self.pushButton_L_sure.setText(_translate("MainWindow", "确认"))
import res_rc
